---
- name: "Playbook to install software"
  hosts: all
  become: true
  vars:
      packages: wget
  tasks:
  - name: "Subscribe the VM with a specific Pool ID"
    redhat_subscription:
      state: present
      username: "{{rhn_user}}"
      password: "{{rhn_user_password}}"
      #      pool_ids: 0123456789abcdef0123456789abcdef

  - name: "Install Software"
    yum: state=present name="{{packages | regex_replace(',')}}"
    #    environment: 
    #      http_proxy: http://theproxy.com:3128
    #      ignore_errors: yes
